import {
  InvestmentModel,
  RoiAssumptions,
  City,
  RoadmapStep,
  Faq,
  ResourceDocument,
  SiteSettings,
  Lead
} from '../src/types';

export const initialSiteSettings: SiteSettings = {
  company_name: 'Sugartown Retail Private Limited',
  phone: '9145448010',
  email: 'info@sugartown.in',
  website: 'www.sugartownindia.com',
  office_address: '702, Workflow, Icon Tower, Laxminagar, Baner, Pune 411045, Maharashtra, India',
  brand_color: '#FC3D00',
  whatsapp_number: '9145448010',
  notification_email: 'info@sugartown.in',
};

export const initialInvestmentModels: InvestmentModel[] = [
  {
    id: 'model-25l',
    code: '25L',
    title: 'Express Kiosk & High-Street Boutique',
    tag: 'Compact Experiential Format',
    total_investment: 2500000,
    store_format: 'Kiosk / High-Street Express',
    area_sqft: '150 – 250 sq.ft',
    display_order: 1,
    description:
      'Engineered for premium mall atriums, transit hubs, and boutique high streets. Features our signature compact Live Candy Theater workstation, high-margin retail pick-and-mix, and curated gifting lines.',
    active: true,
    components: [
      {
        id: 'c-25-1',
        model_id: 'model-25l',
        category: 'Brand / Franchise Fee',
        name: 'Franchise Onboarding & 5-Year Brand Rights',
        amount: 500000,
        percentage: 20,
        display_order: 1,
        status: 'included',
        notes: 'Includes trademark license, territory exclusivity rights, and corporate setup.',
      },
      {
        id: 'c-25-2',
        model_id: 'model-25l',
        category: 'Interior & Civil Fit-out',
        name: 'Turnkey Architectural & Civil Works',
        amount: 750000,
        percentage: 30,
        display_order: 2,
        status: 'included',
        notes: 'Flooring, bespoke cabinetry, theatrical lighting, illuminated signage, and facade.',
      },
      {
        id: 'c-25-3',
        model_id: 'model-25l',
        category: 'Equipment & Specialized Machinery',
        name: 'Confectionery Processing & Display Fixtures',
        amount: 450000,
        percentage: 18,
        display_order: 3,
        status: 'included',
        notes: 'Temperature-controlled candy heating tables, candy pulling units, and display cases.',
      },
      {
        id: 'c-25-4',
        model_id: 'model-25l',
        category: 'Live Candy Theater',
        name: 'Theatrical Demonstration Stage & Extraction',
        amount: 300000,
        percentage: 12,
        display_order: 4,
        status: 'included',
        notes: 'Live theater glass observation counter, food-grade ventilation, and artisan tools.',
      },
      {
        id: 'c-25-5',
        model_id: 'model-25l',
        category: 'Kitchen / Production',
        name: 'Back-of-House Storage & Sanitary Prep Fixtures',
        amount: 150000,
        percentage: 6,
        display_order: 5,
        status: 'included',
        notes: 'Sanitization sinks, stainless prep stations, and dry ingredient bins.',
      },
      {
        id: 'c-25-6',
        model_id: 'model-25l',
        category: 'Technology & Hardware',
        name: 'POS Terminal, Barcode Scanners & Cloud CCTV',
        amount: 100000,
        percentage: 4,
        display_order: 6,
        status: 'included',
        notes: 'Integrated inventory POS, digital payment terminals, and live security streaming.',
      },
      {
        id: 'c-25-7',
        model_id: 'model-25l',
        category: 'Initial Inventory',
        name: 'Opening Stock & Custom Branded Packaging',
        amount: 150000,
        percentage: 6,
        display_order: 7,
        status: 'included',
        notes: 'Comprehensive assortment of artisan rock candies, lollipops, jars, and gift boxes.',
      },
      {
        id: 'c-25-8',
        model_id: 'model-25l',
        category: 'Training & SOP Onboarding',
        name: 'Artisan Staff Certification Program',
        amount: 50000,
        percentage: 2,
        display_order: 8,
        status: 'included',
        notes: 'Intensive culinary theater training, customer engagement, and health-safety SOPs.',
      },
      {
        id: 'c-25-9',
        model_id: 'model-25l',
        category: 'Launch Marketing',
        name: 'Grand Opening Activation & PR Support',
        amount: 50000,
        percentage: 2,
        display_order: 9,
        status: 'included',
        notes: 'Local influencer invites, opening week tastings, collateral, and geo-targeted ads.',
      },
      {
        id: 'c-25-10',
        model_id: 'model-25l',
        category: 'Working Capital',
        name: 'Operating Float / Buffer',
        amount: 0,
        display_order: 10,
        status: 'configurable',
        notes: 'Recommended ₹50k–₹1L partner operational liquidity based on location.',
      },
    ],
  },
  {
    id: 'model-50l',
    code: '50L',
    title: 'Flagship Experiential Theater Lounge',
    tag: 'Signature Destination Store',
    total_investment: 5000000,
    store_format: 'Flagship Store / Experiential Lounge',
    area_sqft: '400 – 750 sq.ft',
    display_order: 2,
    description:
      'Our premier full-scale concept built for destination shopping centers and luxury high streets. Houses a 360-degree immersive Live Candy Theater stage, custom masterclasses, personalized gifting bar, and high-volume retail.',
    active: true,
    components: [
      {
        id: 'c-50-1',
        model_id: 'model-50l',
        category: 'Brand / Franchise Fee',
        name: 'Franchise Master License & 5-Year Rights',
        amount: 800000,
        percentage: 16,
        display_order: 1,
        status: 'included',
        notes: 'Flagship tier territory protection, master recipes, and corporate executive support.',
      },
      {
        id: 'c-50-2',
        model_id: 'model-50l',
        category: 'Interior & Civil Fit-out',
        name: 'Premium Architectural Lounge & Civil Fit-out',
        amount: 1600000,
        percentage: 32,
        display_order: 2,
        status: 'included',
        notes: 'Acoustic treatment, high-end display arches, custom terrazzo, lighting & grand storefront.',
      },
      {
        id: 'c-50-3',
        model_id: 'model-50l',
        category: 'Equipment & Specialized Machinery',
        name: 'Industrial Artisan Candy Manufacturing & Hot Tables',
        amount: 900000,
        percentage: 18,
        display_order: 3,
        status: 'included',
        notes: 'Dual programmable heating tables, motorized candy hook/puller, and rolling tables.',
      },
      {
        id: 'c-50-4',
        model_id: 'model-50l',
        category: 'Live Candy Theater',
        name: 'Grand 360° Amphitheater Stage & Air Scrubbers',
        amount: 650000,
        percentage: 13,
        display_order: 4,
        status: 'included',
        notes: 'Surround seating/viewing bar, overhead live-demonstration video feeds, and sound system.',
      },
      {
        id: 'c-50-5',
        model_id: 'model-50l',
        category: 'Kitchen / Production',
        name: 'Cold Storage, Prep Kitchen & Artisan Gifting Bar',
        amount: 350000,
        percentage: 7,
        display_order: 5,
        status: 'included',
        notes: 'Refrigerated ingredient units, vacuum sealers, ribbon printing and bespoke gift packing station.',
      },
      {
        id: 'c-50-6',
        model_id: 'model-50l',
        category: 'Technology & Hardware',
        name: 'Dual POS, Digital Signage Array & Security',
        amount: 200000,
        percentage: 4,
        display_order: 6,
        status: 'included',
        notes: 'Multi-register billing, customer feedback iPads, digital price menus, and audio control.',
      },
      {
        id: 'c-50-7',
        model_id: 'model-50l',
        category: 'Initial Inventory',
        name: 'Flagship Opening Inventory & Luxury Gift Sets',
        amount: 300000,
        percentage: 6,
        display_order: 7,
        status: 'included',
        notes: 'Extended SKU inventory, seasonal collector tins, corporate gifting sample hampers.',
      },
      {
        id: 'c-50-8',
        model_id: 'model-50l',
        category: 'Training & SOP Onboarding',
        name: 'Comprehensive Master Artisan Certification',
        amount: 100000,
        percentage: 2,
        display_order: 8,
        status: 'included',
        notes: '2-week full team residency training in Pune HQ covering entertainment theater & operations.',
      },
      {
        id: 'c-50-9',
        model_id: 'model-50l',
        category: 'Launch Marketing',
        name: 'High-Impact Brand Launch Campaign & PR Gala',
        amount: 100000,
        percentage: 2,
        display_order: 9,
        status: 'included',
        notes: 'City-wide digital press release, food critic preview event, and celebrity candy workshops.',
      },
      {
        id: 'c-50-10',
        model_id: 'model-50l',
        category: 'Working Capital',
        name: 'Working Capital Reserve',
        amount: 0,
        display_order: 10,
        status: 'configurable',
        notes: 'Recommended ₹1.5L–₹2.5L partner operating buffer based on lease dynamics.',
      },
    ],
  },
];

export const initialRoiAssumptions: RoiAssumptions[] = [
  {
    id: 'roi-25l',
    model_id: 'model-25l',
    model_code: '25L',
    default_monthly_revenue: 1000000,
    default_cogs_percent: 40,
    default_operating_expenses: 300000,
    default_foco_percent: 8,
    default_foco_fixed: 0,
    foco_mode: 'percentage',
    default_other_costs: 25000,
    default_annual_growth_percent: 10,
    tax_percent: 0,
    updated_at: new Date().toISOString(),
    updated_by: 'System Administrator',
  },
  {
    id: 'roi-50l',
    model_id: 'model-50l',
    model_code: '50L',
    default_monthly_revenue: 1800000,
    default_cogs_percent: 38,
    default_operating_expenses: 520000,
    default_foco_percent: 8,
    default_foco_fixed: 0,
    foco_mode: 'percentage',
    default_other_costs: 40000,
    default_annual_growth_percent: 12,
    tax_percent: 0,
    updated_at: new Date().toISOString(),
    updated_by: 'System Administrator',
  },
];

export const initialCities: City[] = [
  {
    id: 'city-pune',
    city_name: 'Pune',
    state: 'Maharashtra',
    tier: 'Tier 1',
    latitude: 18.5204,
    longitude: 73.8567,
    status: 'Existing',
    priority: 1,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Flagship Store / High-Street Boutique',
    territory_available: true,
    store_count: 2,
    market_notes: 'Sugartown Corporate HQ & flagship market. High-density affluent neighborhoods in Baner, Koregaon Park, Kalyani Nagar & Phoenix Marketcity.',
    description: 'Corporate flagship operations active. Expansion open for select suburban high-street micro-markets.',
  },
  {
    id: 'city-mumbai',
    city_name: 'Mumbai',
    state: 'Maharashtra',
    tier: 'Tier 1',
    latitude: 19.0760,
    longitude: 72.8777,
    status: 'Priority',
    priority: 1,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Flagship Experiential Lounge',
    territory_available: true,
    market_notes: 'India’s premier retail & luxury market. High demand in Bandra, Lower Parel (Palladium), Juhu, Powai, and Thane.',
    description: 'Prime target for flagship experiential theaters with massive corporate gifting and event opportunities.',
  },
  {
    id: 'city-bengaluru',
    city_name: 'Bengaluru',
    state: 'Karnataka',
    tier: 'Tier 1',
    latitude: 12.9716,
    longitude: 77.5946,
    status: 'Priority',
    priority: 1,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Flagship Experiential Lounge',
    territory_available: true,
    market_notes: 'High disposable income tech population. Prime corridors: Indiranagar 100ft Road, Koramangala, Phoenix Mall of Asia (Hebbal), Whitefield.',
    description: 'Ideal demographic profile for experiential confectionery and tech-integrated live candy theater.',
  },
  {
    id: 'city-delhi',
    city_name: 'Delhi NCR',
    state: 'Delhi / Haryana',
    tier: 'Tier 1',
    latitude: 28.6139,
    longitude: 77.2090,
    status: 'Priority',
    priority: 1,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Flagship Store',
    territory_available: true,
    market_notes: 'Enormous wedding, festive, and experiential gifting market. Target locations: CyberHub Gurgaon, Select Citywalk Saket, Mall of India Noida.',
    description: 'Extremely strong gifting culture with high average transaction value for customized rock confectionery.',
  },
  {
    id: 'city-hyderabad',
    city_name: 'Hyderabad',
    state: 'Telangana',
    tier: 'Tier 1',
    latitude: 17.3850,
    longitude: 78.4867,
    status: 'Priority',
    priority: 2,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'High-Street Boutique / Mall Kiosk',
    territory_available: true,
    market_notes: 'Jubilee Hills Road No. 36, Banjara Hills, Inorbit Cyberabad, and Sarath City Capital Mall.',
    description: 'Rapidly growing cosmopolitan hub with strong affinity for premium artisanal sweets and celebrations.',
  },
  {
    id: 'city-ahmedabad',
    city_name: 'Ahmedabad',
    state: 'Gujarat',
    tier: 'Tier 1',
    latitude: 23.0225,
    longitude: 72.5714,
    status: 'Priority',
    priority: 2,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'High-Street Flagship Lounge',
    territory_available: true,
    market_notes: 'Unrivaled sweet consumption, family evening outings, and wedding gifting demand. SG Highway & Sindhu Bhavan Road.',
    description: 'Key strategic market with family dining culture and highest dessert per capita spending.',
  },
  {
    id: 'city-chennai',
    city_name: 'Chennai',
    state: 'Tamil Nadu',
    tier: 'Tier 1',
    latitude: 13.0827,
    longitude: 80.2707,
    status: 'Under Evaluation',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Mall Atrium Kiosk',
    territory_available: false,
    market_notes: 'Express Avenue, Phoenix Marketcity Velachery, VR Chennai under feasibility study.',
    description: 'Territory currently under technical and footfall assessment by retail analytics team.',
  },
  {
    id: 'city-kolkata',
    city_name: 'Kolkata',
    state: 'West Bengal',
    tier: 'Tier 1',
    latitude: 22.5726,
    longitude: 88.3639,
    status: 'Under Evaluation',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Boutique Kiosk',
    territory_available: false,
    market_notes: 'Park Street, South City Mall, Quest Mall evaluated for festival seasonality.',
    description: 'Market assessment in progress for upcoming festive calendar expansion.',
  },
  {
    id: 'city-surat',
    city_name: 'Surat',
    state: 'Gujarat',
    tier: 'Tier 2',
    latitude: 21.1702,
    longitude: 72.8311,
    status: 'Available',
    priority: 2,
    investment_model: '₹25L',
    suggested_format: 'High-Street Express',
    territory_available: true,
    market_notes: 'Vesu, VIP Road, and Dumas Road. Incredible appetite for premium celebratory gifting and novelty desserts.',
    description: 'High purchasing power with entrepreneurial community receptive to FOCO retail concepts.',
  },
  {
    id: 'city-jaipur',
    city_name: 'Jaipur',
    state: 'Rajasthan',
    tier: 'Tier 2',
    latitude: 26.9124,
    longitude: 75.7873,
    status: 'Available',
    priority: 2,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Experiential Boutique',
    territory_available: true,
    market_notes: 'C-Scheme, Malviya Nagar, World Trade Park. Blend of luxury tourist footfall and destination weddings.',
    description: 'High synergy with custom bridal favors, personalized candy messaging, and international tourists.',
  },
  {
    id: 'city-chandigarh',
    city_name: 'Chandigarh',
    state: 'Punjab / Haryana',
    tier: 'Tier 2',
    latitude: 30.7333,
    longitude: 76.7794,
    status: 'Priority',
    priority: 2,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Flagship Store / Kiosk',
    territory_available: true,
    market_notes: 'Elante Mall, Sector 8/9/17 inner markets. High per capita lifestyle expenditure.',
    description: 'Strong youth and family demographic with appetite for experiential retail and Instagrammable theater.',
  },
  {
    id: 'city-indore',
    city_name: 'Indore',
    state: 'Madhya Pradesh',
    tier: 'Tier 2',
    latitude: 22.7196,
    longitude: 75.8577,
    status: 'Available',
    priority: 2,
    investment_model: '₹25L',
    suggested_format: 'Express Boutique',
    territory_available: true,
    market_notes: 'Commercial capital of MP. Vijay Nagar, 56 Dukan neighborhood, C21 Mall.',
    description: 'Celebrated culinary culture where experiential treats and novelty products capture viral interest.',
  },
  {
    id: 'city-lucknow',
    city_name: 'Lucknow',
    state: 'Uttar Pradesh',
    tier: 'Tier 2',
    latitude: 26.8467,
    longitude: 80.9462,
    status: 'Available',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Express Boutique',
    territory_available: true,
    market_notes: 'Lulu Mall Lucknow, Phoenix Palassio, Hazratganj.',
    description: 'Rapidly modernizing retail landscape with booming destination malls.',
  },
  {
    id: 'city-goa',
    city_name: 'Goa',
    state: 'Goa',
    tier: 'Tier 2',
    latitude: 15.2993,
    longitude: 74.1240,
    status: 'Priority',
    priority: 2,
    investment_model: '₹25L & ₹50L',
    suggested_format: 'Experiential Boutique Lounge',
    territory_available: true,
    market_notes: 'Panaji Promenade, Candolim, Mall de Goa. High-density holiday tourist footfall year-round.',
    description: 'Exceptional tourist souvenir and experiential attraction opportunity.',
  },
  {
    id: 'city-kochi',
    city_name: 'Kochi',
    state: 'Kerala',
    tier: 'Tier 2',
    latitude: 9.9312,
    longitude: 76.2673,
    status: 'Under Evaluation',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Mall Atrium Kiosk',
    territory_available: false,
    market_notes: 'Lulu International Shopping Mall Edappally, Marine Drive.',
    description: 'High footfall mall location under review for next expansion phase.',
  },
  {
    id: 'city-nagpur',
    city_name: 'Nagpur',
    state: 'Maharashtra',
    tier: 'Tier 2',
    latitude: 21.1458,
    longitude: 79.0882,
    status: 'Available',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Express Boutique',
    territory_available: true,
    market_notes: 'VR Mall, Ramdaspeth, Sadar.',
    description: 'Strategic central Maharashtra hub connecting Vidarbha consumer base.',
  },
  {
    id: 'city-vadodara',
    city_name: 'Vadodara',
    state: 'Gujarat',
    tier: 'Tier 2',
    latitude: 22.3072,
    longitude: 73.1812,
    status: 'Available',
    priority: 3,
    investment_model: '₹25L',
    suggested_format: 'Mall Kiosk / High-Street',
    territory_available: true,
    market_notes: 'Inorbit Mall, Alkapuri.',
    description: 'Strong cultural and NRI gifting center.',
  },
  {
    id: 'city-coimbatore',
    city_name: 'Coimbatore',
    state: 'Tamil Nadu',
    tier: 'Tier 2',
    latitude: 11.0168,
    longitude: 76.9558,
    status: 'Available',
    priority: 4,
    investment_model: '₹25L',
    suggested_format: 'Express Kiosk',
    territory_available: true,
    market_notes: 'Brookefields Mall, RS Puram.',
    description: 'Industrial wealth hub with stable consumer purchasing power.',
  },
  {
    id: 'city-nashik',
    city_name: 'Nashik',
    state: 'Maharashtra',
    tier: 'Tier 3',
    latitude: 19.9975,
    longitude: 73.7898,
    status: 'Available',
    priority: 4,
    investment_model: '₹25L',
    suggested_format: 'Express Kiosk',
    territory_available: true,
    market_notes: 'College Road, City Centre Mall.',
    description: 'Expanding Tier 3 city proximate to Mumbai/Pune logistics corridor.',
  },
  {
    id: 'city-udaipur',
    city_name: 'Udaipur',
    state: 'Rajasthan',
    tier: 'Tier 3',
    latitude: 24.5854,
    longitude: 73.7125,
    status: 'Available',
    priority: 4,
    investment_model: '₹25L',
    suggested_format: 'Heritage Boutique',
    territory_available: true,
    market_notes: 'Celebration Mall, Old City Heritage Precinct.',
    description: 'Global wedding destination with massive demand for custom artisanal favors.',
  },
];

export const initialRoadmapSteps: RoadmapStep[] = [
  {
    id: 'step-1',
    step_number: 1,
    title: 'Inquiry & Eligibility Screening',
    phase: 'Discovery',
    description: 'Submit your franchise inquiry with preferred territory, investment capacity, and background.',
    expected_action: 'Complete digital inquiry form and provide initial financial verification.',
    partner_responsibility: 'Submit profile, identify target geography, and declare investment readiness.',
    sugartown_responsibility: 'Review candidate profile against regional territory availability within 48 hours.',
    estimated_duration: '1–2 Days',
  },
  {
    id: 'step-2',
    step_number: 2,
    title: 'Brand Discovery & Model Review',
    phase: 'Discovery',
    description: 'Participate in an interactive discovery session with the Sugartown corporate team.',
    expected_action: 'Deep dive into the FOCO structure, experiential candy theater concept, and financial models.',
    partner_responsibility: 'Attend discovery meeting / video conference and clarify commercial questions.',
    sugartown_responsibility: 'Present detailed unit economics, store formats, and historical performance metrics.',
    estimated_duration: '3–5 Days',
  },
  {
    id: 'step-3',
    step_number: 3,
    title: 'Territory Evaluation & Micro-Market Analysis',
    phase: 'Feasibility',
    description: 'Collaborate with our retail analytics team to identify prime high-footfall mall or high-street locations.',
    expected_action: 'Review catchment demographics, footfall density, competitor presence, and lease economics.',
    partner_responsibility: 'Shortlist preferred mall or high-street retail zones in the chosen city.',
    sugartown_responsibility: 'Conduct professional catchment mapping, technical viability, and footfall audits.',
    estimated_duration: '1–2 Weeks',
  },
  {
    id: 'step-4',
    step_number: 4,
    title: 'Committee Approval & Letter of Intent (LOI)',
    phase: 'Commitment',
    description: 'Formal review by Sugartown franchise committee and issuance of provisional territory allocation.',
    expected_action: 'Sign Letter of Intent and secure exclusive territory locking deposit.',
    partner_responsibility: 'Sign LOI and submit refundable territory reservation token.',
    sugartown_responsibility: 'Lock territory exclusivity for 45 days and issue store design initiation pack.',
    estimated_duration: '3–7 Days',
  },
  {
    id: 'step-5',
    step_number: 5,
    title: 'Franchise Agreement & Lease Finalization',
    phase: 'Legal & Property',
    description: 'Execution of the comprehensive 5-year FOCO Franchise Agreement and commercial retail lease.',
    expected_action: 'Finalize store lease agreement with mall developer or property owner and sign FOCO contracts.',
    partner_responsibility: 'Execute franchise agreement and complete lease formalities with landlord.',
    sugartown_responsibility: 'Assist in lease negotiation, commercial terms vetting, and deliver legal documentation.',
    estimated_duration: '1–2 Weeks',
  },
  {
    id: 'step-6',
    step_number: 6,
    title: 'Store Architecture & Fit-out Execution',
    phase: 'Setup',
    description: 'Turnkey architectural buildout, live candy theater installation, ventilation, and custom fixtures.',
    expected_action: 'Sugartown corporate project team oversees 100% of the fit-out to exact brand specifications.',
    partner_responsibility: 'Disburse fit-out tranches as per verified project milestones.',
    sugartown_responsibility: 'Deliver 3D architectural renders, execute contractor works, install machines & theater.',
    estimated_duration: '3–4 Weeks',
  },
  {
    id: 'step-7',
    step_number: 7,
    title: 'Artisan Staffing & Master Certification',
    phase: 'Training',
    description: 'Recruitment and intensive culinary theater training of store artisans and operational crew.',
    expected_action: '2-week comprehensive training program on live candy pulling, food safety, POS, and hospitality.',
    partner_responsibility: 'Review team onboarding updates.',
    sugartown_responsibility: 'Recruit, train, and certify master candy makers and retail staff with corporate SOPs.',
    estimated_duration: '2 Weeks',
  },
  {
    id: 'step-8',
    step_number: 8,
    title: 'Grand Launch & PR Campaign',
    phase: 'Launch',
    description: 'Spectacular store inauguration with live candy demonstrations, influencer activations, and local media.',
    expected_action: 'Opening week tasting festivals, VIP creator invites, and digital geo-targeted promotions.',
    partner_responsibility: 'Attend inaugural ribbon-cutting ceremony and celebrate with the team.',
    sugartown_responsibility: 'Deploy corporate launch managers, execute opening marketing blitz, and optimize initial flow.',
    estimated_duration: 'Launch Week',
  },
  {
    id: 'step-9',
    step_number: 9,
    title: 'Company-Operated Daily Management',
    phase: 'Operations',
    description: 'Sugartown takes full operational charge: ingredient supply chain, quality audits, staffing, and POS.',
    expected_action: 'End-to-end management ensuring consistent consumer experience and transparent revenue reporting.',
    partner_responsibility: 'Review automated weekly / monthly financial performance dashboards.',
    sugartown_responsibility: 'Daily store operations, inventory logistics, employee payroll, customer service & audits.',
    estimated_duration: 'Ongoing',
  },
  {
    id: 'step-10',
    step_number: 10,
    title: 'Scale & Multi-Unit Opportunities',
    phase: 'Growth',
    description: 'Continuous marketing innovation, seasonal gifting expansion, and priority rights to additional territories.',
    expected_action: 'Periodic business reviews to optimize profitability and evaluate second/third unit expansion.',
    partner_responsibility: 'Participate in quarterly strategic business reviews and explore multi-unit scaling.',
    sugartown_responsibility: 'Introduce new SKU lines, seasonal festival campaigns, and offer first-right on new city zones.',
    estimated_duration: 'Long-term',
  },
];

export const initialFaqs: Faq[] = [
  {
    id: 'faq-1',
    category: 'FOCO',
    question: 'What is the FOCO model and how does it benefit the franchise partner?',
    answer:
      'FOCO stands for "Franchise Owned, Company Operated". In this model, you provide the initial capital and own the physical franchise asset and business rights, while Sugartown’s expert corporate team manages 100% of the day-to-day operations—including hiring & training artisan candy makers, supply chain logistics, customer service, and marketing. This allows you to enjoy passive business returns without the operational headaches of running a retail store.',
    display_order: 1,
    published: true,
  },
  {
    id: 'faq-2',
    category: 'Investment',
    question: 'What are the available investment formats and total capital requirements?',
    answer:
      'Sugartown offers two primary investment formats: the ₹25 Lakh Express Kiosk / High-Street Boutique (150–250 sq.ft) ideal for high-density mall atriums and boutique high-streets, and the ₹50 Lakh Flagship Experiential Lounge (400–750 sq.ft) featuring a full 360° Live Candy Theater stage, custom masterclasses, and an expansive gifting lounge. Both formats are turnkey and include franchise fees, interiors, specialized machinery, live theater stage setup, technology, initial stock, and training.',
    display_order: 2,
    published: true,
  },
  {
    id: 'faq-3',
    category: 'ROI',
    question: 'How is profitability calculated and are returns guaranteed?',
    answer:
      'Sugartown does not guarantee financial returns, as all retail performance depends on location, footfall, market conditions, and operational execution. However, our transparent financial model projects an indicative operating margin of 20%–30% with an estimated payback period of 18–30 months under standard business assumptions. Our live ROI Calculator allows you to stress-test these projections with custom revenue and cost variables.',
    display_order: 3,
    published: true,
  },
  {
    id: 'faq-4',
    category: 'Franchise',
    question: 'What makes Sugartown different from ordinary candy or confectionery stores?',
    answer:
      'Sugartown is India’s pioneer in "Live Candy Theater" and experiential retail. Rather than simply selling packaged sweets, we transform confectionery into an engaging sensory performance where customers watch master artisans pull, shape, and hand-craft custom rock candies live on heated stages. This creates unmatched footfall pull, high social media virality, and significant margins through bespoke corporate and wedding gifting.',
    display_order: 4,
    published: true,
  },
  {
    id: 'faq-5',
    category: 'Operations',
    question: 'Who handles staff recruitment, candy-making training, and store staffing?',
    answer:
      'Sugartown corporate headquarters handles end-to-end recruitment, background checks, and master culinary training for all store staff. Our certified artisans undergo rigorous training in candy artistry, food hygiene SOPs, and customer showmanship at our Pune training center before deployment.',
    display_order: 5,
    published: true,
  },
  {
    id: 'faq-6',
    category: 'Territory',
    question: 'How do you assist with site selection and lease negotiations?',
    answer:
      'Our dedicated retail expansion analytics team conducts comprehensive footfall, demographic, and catchment studies before approving any retail location. We actively assist in negotiations with Grade-A mall developers and high-street property owners to secure favorable commercial lease terms and optimal store placement.',
    display_order: 6,
    published: true,
  },
  {
    id: 'faq-7',
    category: 'Support',
    question: 'What ongoing support does Sugartown provide after store launch?',
    answer:
      'Franchise partners receive complete support including centralized raw material and packaging supply chain, cloud-connected POS with real-time financial auditing, national marketing campaigns, festive seasonal SKU releases, continuous staff skill upgrades, and quarterly business performance reviews.',
    display_order: 7,
    published: true,
  },
  {
    id: 'faq-8',
    category: 'Setup',
    question: 'How long does it take from signing the agreement to the grand opening?',
    answer:
      'Typically, the entire process takes between 4 to 8 weeks from lease signing to store launch. This includes turnkey civil & interior fit-out (3–4 weeks), specialized machinery installation, staff onboarding & training (2 weeks), and pre-launch marketing activation.',
    display_order: 8,
    published: true,
  },
];

export const initialDocuments: ResourceDocument[] = [
  {
    id: 'doc-1',
    title: 'Sugartown Franchise Information Memorandum (Deck)',
    category: 'Franchise Overview',
    description: 'Comprehensive brand presentation covering market positioning, Live Candy Theater concept, store layouts, and unit economics.',
    file_url: 'https://drive.google.com/file/d/1o5FHp2LfgTW58gk3g78OIWwn0dfMlcfc/view?usp=drive_link',
    version: 'v2026.1',
    is_public: true,
    file_size: '4.8 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-2',
    title: 'FOCO Operating Structure & Commercial Framework',
    category: 'FOCO Model',
    description: 'Detailed operational breakdown explaining partner responsibilities, company governance, revenue flow, and audit protocols.',
    file_url: 'https://drive.google.com/file/d/1_P82WexZNhHIQ8SLUw6mRqdlwXo3SMsZ/view?usp=drive_link',
    version: 'v2026.1',
    is_public: true,
    file_size: '2.4 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-3',
    title: '₹25L & ₹50L Investment Breakdown & BOQ Specifications',
    category: 'Investment Plan',
    description: 'Itemized cost schedule covering interior fit-out, candy pullers, heating tables, POS hardware, and initial working capital.',
    file_url: 'https://drive.google.com/file/d/1LxT3USc2mdknr0CCc-8u1b8JiJiJkjKO/view?usp=drive_link',
    version: 'v2026.1',
    is_public: true,
    file_size: '1.9 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-4',
    title: '5-Year Unit Economics & Financial Projections Model',
    category: 'Financial Model',
    description: 'Granular financial forecast spreadsheet outlining monthly revenue benchmarks, gross margin dynamics, OpEx, and ROI sensitivity.',
    file_url: 'https://drive.google.com/file/d/1ta68A5PrUasMLtKPyMb65TSkib8wQnaI/view?usp=drive_link',
    version: 'v2026.1',
    is_public: true,
    file_size: '3.1 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-5',
    title: 'India Pan-Regional Expansion Blueprint & City Roadmaps',
    category: 'Expansion Blueprint',
    description: 'Tier 1 & Tier 2 city priority mapping, catchment criteria, and demographic spending indices for upcoming franchise territories.',
    file_url: 'https://drive.google.com/file/d/1eEHx2-28jiPlsOQmIj-8CRwxYOJlFER3/view?usp=drive_link',
    version: 'v2026.1',
    is_public: true,
    file_size: '2.8 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-corp-coi',
    title: 'Certificate of Incorporation (CIN: U47215PN2025PTC243386)',
    category: 'Company Credential',
    description: 'Government of India MCA Certificate of Incorporation for Sugartown Retail Private Limited under Companies Act, 2013.',
    file_url: 'https://www.mca.gov.in',
    version: 'v2025.06',
    is_public: true,
    file_size: '1.2 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-corp-startup-india',
    title: 'DPIIT Startup India Certificate of Recognition (DIPP270712)',
    category: 'Company Credential',
    description: 'Government of India DPIIT recognition certificate in Food & Beverages and Food Processing valid for 10 years.',
    file_url: 'https://www.startupindia.gov.in',
    version: 'v2026.07',
    is_public: true,
    file_size: '890 KB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-corp-fssai',
    title: 'FSSAI Food Safety Registration Certificate (Reg: 21526082001908)',
    category: 'Food Safety',
    description: 'Food Safety and Standards Authority of India (FSSAI) statutory 5-year registration for Confectionery (Category 05).',
    file_url: 'https://foscos.fssai.gov.in',
    version: 'v2026.04',
    is_public: true,
    file_size: '1.4 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-corp-udyam',
    title: 'Udyam MSME Registration Certificate (UDYAM-MH-26-0960597)',
    category: 'Company Credential',
    description: 'Ministry of MSME Government of India registration for confectionery and chocolate manufacturing.',
    file_url: 'https://udyamregistration.gov.in',
    version: 'v2025.08',
    is_public: true,
    file_size: '1.1 MB',
    created_at: new Date().toISOString(),
  },
  {
    id: 'doc-corp-iec',
    title: 'DGFT Importer-Exporter Code Certificate (IEC: ABQCS5950B)',
    category: 'Trade & Import',
    description: 'Ministry of Commerce & Industry DGFT Pune certificate authorizing international machinery imports and global confectionery exports.',
    file_url: 'https://dgft.gov.in',
    version: 'v2026.04',
    is_public: true,
    file_size: '820 KB',
    created_at: new Date().toISOString(),
  },
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-sug-101',
    full_name: 'Rajesh Malhotra',
    mobile: '+919822019485',
    email: 'rajesh.malhotra@malhotragroup.in',
    city: 'Mumbai',
    state: 'Maharashtra',
    profession: 'Retail Investor / Ex-F&B Franchisee',
    investment_capacity: '₹50 Lakh+',
    preferred_city: 'Mumbai',
    business_experience: true,
    business_type: 'Operated multi-brand F&B kiosks in Bandra and Phoenix Palladium',
    experience_years: 12,
    preferred_format: 'Flagship Experiential Lounge (₹50L)',
    message: 'Looking for a prime spot in Palladium or Bandra Linking Road. Love the Live Candy Theater concept.',
    consent: true,
    source: 'Website Inquiry Form',
    utm_source: 'google_search',
    utm_medium: 'cpc',
    utm_campaign: 'franchise_q1',
    status: 'qualified',
    assigned_to: 'Franchise Director',
    notes: [
      {
        id: 'note-1',
        lead_id: 'lead-sug-101',
        author: 'Pooja (Expansion Team)',
        note: 'Completed initial screening call. Applicant has ready liquid capital and retail lease contacts in Lower Parel.',
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'lead-sug-102',
    full_name: 'Ananya Deshmukh',
    mobile: '+919422318720',
    email: 'ananya.deshmukh@gmail.com',
    city: 'Pune',
    state: 'Maharashtra',
    profession: 'Corporate Executive & Angel Investor',
    investment_capacity: '₹25 Lakh',
    preferred_city: 'Pune',
    business_experience: false,
    preferred_format: 'Express Kiosk & High-Street Boutique (₹25L)',
    message: 'Interested in the FOCO model for passive investment in Pune (Koregaon Park / Baner).',
    consent: true,
    source: 'ROI Calculator Flow',
    utm_source: 'direct',
    utm_medium: 'organic',
    utm_campaign: 'roi_calculator',
    status: 'new',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'lead-sug-103',
    full_name: 'Vikramaditya Singhania',
    mobile: '+919811456902',
    email: 'vikram.singhania@apexventure.com',
    city: 'Bengaluru',
    state: 'Karnataka',
    profession: 'Venture Partner & Retail Property Owner',
    investment_capacity: '₹50 Lakh+',
    preferred_city: 'Bengaluru',
    business_experience: true,
    business_type: 'Commercial real estate landlord and franchise investor',
    experience_years: 15,
    preferred_format: 'Flagship Experiential Lounge (₹50L)',
    message: 'Have an owned 600 sq ft space on Indiranagar 100ft road. Want to discuss exclusivity for Bangalore East.',
    consent: true,
    source: 'India Expansion Map Flow',
    utm_source: 'linkedin',
    utm_medium: 'social',
    utm_campaign: 'bengaluru_expansion',
    status: 'site_evaluation',
    assigned_to: 'Head of Expansion',
    notes: [
      {
        id: 'note-2',
        lead_id: 'lead-sug-103',
        author: 'Aditya (City Head)',
        note: 'Site photos received. Location has excellent 40ft frontage on Indiranagar 100ft road. Scheduled site audit for Friday.',
        created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const initialLois: any[] = [
  {
    id: 'loi-sug-901',
    loi_number: 'ST-LOI-2026-0891',
    full_name: 'Rajesh Mehra',
    entity_type: 'individual',
    entity_name: 'Mehra Hospitality Ventures',
    pan_number: 'AABCM1982K',
    aadhaar_or_id: 'XXXX-XXXX-4892',
    email: 'rajesh.mehra@gmail.com',
    phone: '+919822019482',
    whatsapp: '+919822019482',
    current_address: 'B-402, Clover Highlands, NIBM Road, Kondhwa',
    current_city: 'Pune',
    current_state: 'Maharashtra',
    pin_code: '411048',
    profession_background: 'Hospitality Investor & Multi-brand F&B Operator',
    existing_business_details: 'Owner of 2 QSR franchises and commercial property in West Pune.',
    investment_model: 'Flagship Live Candy Theater & Experience Store (₹50L)',
    investment_amount_committed: 5000000,
    target_city: 'Pune',
    target_state: 'Maharashtra',
    preferred_location: 'Phoenix Marketcity Viman Nagar or Seasons Mall Magarpatta',
    site_status: 'identifying',
    proposed_carpet_area_sqft: 550,
    source_of_funds: 'self_liquid',
    target_launch_timeline: '45_days',
    accepts_foco_model: true,
    accepts_confidentiality_nda: true,
    accepts_commercial_terms: true,
    territory_exclusivity_requested: true,
    signatory_name: 'Rajesh Mehra',
    signatory_title: 'Principal Investor',
    submission_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'under_review',
    admin_notes: 'High-intent investor with liquid capital. Requested territory exclusivity for East Pune.',
    assigned_manager: 'Aditya (VP Expansion)',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'loi-sug-902',
    loi_number: 'ST-LOI-2026-0894',
    full_name: 'Vikramaditya Singhania',
    entity_type: 'private_limited',
    entity_name: 'Apex Venture Retail Holdings Pvt Ltd',
    pan_number: 'AAACA7412E',
    email: 'vikram.singhania@apexventure.com',
    phone: '+919811456902',
    whatsapp: '+919811456902',
    current_address: 'Apex Tower, 100ft Road, Indiranagar',
    current_city: 'Bengaluru',
    current_state: 'Karnataka',
    pin_code: '560038',
    profession_background: 'Commercial Real Estate Landlord & Franchise Investor',
    existing_business_details: 'Owner of commercial retail building with direct frontage.',
    investment_model: 'Flagship Live Candy Theater & Experience Store (₹50L)',
    investment_amount_committed: 5000000,
    target_city: 'Bengaluru',
    target_state: 'Karnataka',
    preferred_location: 'Indiranagar 100ft Road (Self-owned 600 sq ft unit)',
    site_status: 'owned',
    proposed_carpet_area_sqft: 620,
    source_of_funds: 'self_liquid',
    target_launch_timeline: '30_days',
    accepts_foco_model: true,
    accepts_confidentiality_nda: true,
    accepts_commercial_terms: true,
    territory_exclusivity_requested: true,
    signatory_name: 'Vikramaditya Singhania',
    signatory_title: 'Managing Director',
    submission_date: new Date(Date.now() - 86400000 * 4).toISOString(),
    status: 'due_diligence',
    admin_notes: 'Site inspection completed on Indiranagar 100ft road. Exceptional footfall density.',
    assigned_manager: 'Aditya (VP Expansion)',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  }
];

